### ISSUE TITLE
p2pool/bitcoin/networks/digibyte.py RPC and P2P ports wrong

### ISSUE THREAD

**Issue by oelke** [ilsawa/p2pool-dgb-skein#1]
Edit lines:
P2P_PORT = 12024
RPC_PORT = 14022
(these are the right values for digibyte)

**Comment by ilsawa** [comment]
This is not an error. I have 5 digibyte daemons for different algorithms on my server:
```
#!/bin/bash

su -c '/usr/local/bin/digibyted' groestl
su -c '/usr/local/bin/digibyted' qubit
su -c '/usr/local/bin/digibyted' scrypt
su -c '/usr/local/bin/digibyted' sha256d
su -c '/usr/local/bin/digibyted' skein

```
All daemons can not occupy the same RPC and P2P ports.
Therefore, if you use daemons running in several algorithms on the same server, there is a need to move ports to free ones.
For example, port 14022 uses the digibyte daemon on the groestl algorithm https://github.com/ilsawa/p2pool-dgb-groestl/blob/master/p2pool/bitcoin/networks/digibyte.py#L13

Accordingly, for each instance, I create a user and a configuration file in the user directory ~/.digibyte/digibyte.conf

For example, for the skein algorithm in skein user directory
```
rpcuser=rpc_user
rpcpassword=rpc_password
listenonion=0
listen=1
daemon=1
server=1
gen=0
algo=skein
onlynet=IPv4
rpcworkqueue=32
rpcthreads=96
rpcallowip=127.0.0.1
rpcport=14025
port=12027
irc=0
```
